version: '3.7'

services:
  gtt:
    build:
      context: .
      target: development
    command: yarn start
    env_file:
      - .env
    ports:
      - 8181:80
    volumes:
      - .:/home/node/app
      - gtt_nodemodules:/home/node/app/node_modules

volumes:
  gtt_nodemodules: